# Generated by Django 5.2.11 on 2026-04-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'أنثى'), ('M', 'ذكر')], max_length=1),
        ),
    ]
