# Generated by Django 5.2.11 on 2026-04-30 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extract', '__first__'),
        ('project', '0003_remove_document_content_document_template_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('pending_file', models.FileField(blank=True, null=True, upload_to='pending/')),
                ('generated_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('EXTRACTED', 'Extracted'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generated', to='project.document')),
                ('extraction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='extract.extraction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
