# Generated by Django 5.2.11 on 2026-05-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generateddocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROGRESS', 'In Progress'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
    ]
