# Generated by Django 5.2.11 on 2026-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcript',
            name='processed_text',
        ),
        migrations.RemoveField(
            model_name='transcript',
            name='raw_text',
        ),
        migrations.AddField(
            model_name='transcript',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='processed_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transcript',
            name='source',
            field=models.CharField(choices=[('hybrid', 'hybrid')], default='hybrid', max_length=20),
        ),
    ]
