# Generated by Django 5.2.11 on 2026-04-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preprocessing', '0002_remove_transcript_processed_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcript',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
