# Generated by Django 5.2.11 on 2026-02-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_date',
        ),
    ]
