# Generated by Django 5.2.11 on 2026-02-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_meeting_meeting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='extracted_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='generated_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('EXTRACTED', 'EXTRACTED'), ('GENERATED', 'GENERATED'), ('FAILED', 'FAILED')], default='DRAFT', max_length=20),
        ),
    ]
