# Generated by Django 5.2.13 on 2026-04-22 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_document_extracted_json_document_generated_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='document',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='True after user clicks Approve in the review popup.'),
        ),
        migrations.AddField(
            model_name='document',
            name='pending_file',
            field=models.FileField(blank=True, null=True, upload_to='pending/'),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('BRD', 'Business Requirements Document'), ('MOM', 'Minutes of Meeting'), ('SRS', 'Software Requirements Specification')], default='BRD', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('EXTRACTED', 'Extracted'), ('GENERATED', 'Generated'), ('APPROVED', 'Approved'), ('FAILED', 'Failed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='project.project'),
        ),
    ]
