# Generated by Django 5.2.11 on 2026-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_document_content_document_template_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('joining', 'Joining'), ('recording', 'Recording'), ('ended', 'Ended'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
