# Generated by Django 5.2.11 on 2026-05-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('joining', 'Joining'), ('in_meeting', 'In Meeting'), ('ended', 'Ended'), ('post_meeting', 'Post Meeting'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
