# Generated by Django 5.2.11 on 2026-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_meeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('joining', 'Joining'), ('in_meeting', 'In Meeting'), ('ended', 'Ended'), ('post_meeting', 'Post Meeting'), ('transcribing', 'Transcribing'), ('transcribed', 'Transcribed')], default='created', max_length=20),
        ),
    ]
