# Generated by Django 5.2.11 on 2026-04-30 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processing', '0001_initial'),
        ('project', '0003_remove_document_content_document_template_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filled_schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chunk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions', to='processing.transcriptchunk')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='project.document')),
            ],
        ),
    ]
