# Generated by Django 5.2.12 on 2026-04-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0002_momextraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brdextraction',
            name='extracted_data',
        ),
        migrations.AddField(
            model_name='brdextraction',
            name='filled_schema',
            field=models.JSONField(default=dict),
        ),
    ]
