# Generated by Django 5.2.12 on 2026-04-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0003_remove_brdextraction_extracted_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brdextraction',
            name='filled_schema',
        ),
        migrations.AddField(
            model_name='brdextraction',
            name='extracted_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
