# Generated by Django 5.2.12 on 2026-04-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_remove_brdextraction_filled_schema_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brdextraction',
            old_name='extracted_data',
            new_name='filled_schema',
        ),
        migrations.RenameField(
            model_name='momextraction',
            old_name='extracted_data',
            new_name='filled_schema',
        ),
    ]
