# Generated by Django 5.2.11 on 2026-04-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocessing', '0002_remove_transcript_processed_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('chunk_text', models.TextField()),
                ('semantic_english_text', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='preprocessing.transcript')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
    ]
